/** Host-plane analyst tools (closed profile, no skill). Keep in sync with scripts/product-composition.mjs */
export const HOST_ANALYST_TOOLS = [
  'add_to_dashboard',
  'apply_dashboard_filters',
  'bin_elapsed_intervals',
  'cancel_job',
  'check_studio_availability',
  'create_dashboard',
  'dataset_status',
  'delete_dashboard',
  'describe_column',
  'duckdb_query',
  'export_dashboard',
  'export_report',
  'find_duplicate_rows',
  'find_top_n',
  'get_analysis',
  'get_dashboard',
  'get_learning_examples',
  'get_metrics',
  'get_schema',
  'get_workflow_trail',
  'ingest_dataset',
  'investigate_metric',
  'kaggle_download',
  'list_analyses',
  'list_chart_feedback',
  'list_dashboards',
  'list_datasets',
  'list_pending_metrics',
  'list_pending_structure',
  'make_chart',
  'map_dashboard_filters',
  'preview_ingest_source',
  'propose_metric',
  'propose_sql_correction',
  'propose_structure',
  'ratio_of_sums',
  'reconcile_totals',
  'rename_dashboard',
  'report_chart_issue',
  'resolve_kaggle_source',
  'resolve_kaggle_version',
  'restore_dashboard',
  'save_analysis',
  'search_kaggle_sources',
] as const

export const PRODUCT_ANALYST_TOOLS = [...HOST_ANALYST_TOOLS, 'skill'].sort()
