/**
 * Runtime-only adversarial fixture generation for the versatility gate.
 *
 * Every fixture is built in a temp directory during a gate run and deleted
 * afterwards: this repository distributes no sample datasets
 * (`.gitignore` keeps `datasets/*` and `*.duckdb` out of the tree, and
 * `scripts/public-readiness.mjs` refuses a committed `.duckdb`), so the gate
 * must produce its own messy inputs on demand.
 *
 * Nothing here is model-facing: these builders are importable only from the
 * gate script and its tests, never registered as a tool.
 */
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { DuckDBInstance } from '@duckdb/node-api'

export interface FixtureFile {
  name: string
  bytes: Buffer
}

export type Cell = string | number | null | undefined

/** RFC4180 field quoting — the same escaping a real export tool would emit. */
export function csvField(value: Cell): string {
  const text = value === null || value === undefined ? '' : String(value)
  return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text
}

/** Build CSV bytes from rows (first row is the header when the case wants one). */
export function csvBytes(rows: readonly (readonly Cell[])[]): Buffer {
  return Buffer.from(`${rows.map((row) => row.map(csvField).join(',')).join('\n')}\n`, 'utf8')
}

/**
 * windows-1252 bytes. The gate only uses characters whose byte value is
 * identical in windows-1252 and latin1 (é 0xE9, ø 0xF8, ü 0xFC), which is what
 * a real "ANSI" CSV export of those letters contains.
 */
export function windows1252Bytes(text: string): Buffer {
  for (const character of text) {
    if (character.codePointAt(0)! > 0xff) {
      throw new Error(`windows1252Bytes only supports latin1-range fixture text: ${character}`)
    }
  }
  return Buffer.from(text, 'latin1')
}

/** UTF-16LE bytes with a BOM, as Excel/Notepad "Unicode" export produces. */
export function utf16leWithBomBytes(text: string): Buffer {
  return Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from(text, 'utf16le')])
}

export function utf16beWithBomBytes(text: string): Buffer {
  const littleEndian = Buffer.from(text, 'utf16le')
  const bigEndian = Buffer.alloc(littleEndian.length)
  for (let index = 0; index < littleEndian.length; index += 2) {
    bigEndian[index] = littleEndian[index + 1]!
    bigEndian[index + 1] = littleEndian[index]!
  }
  return Buffer.concat([Buffer.from([0xfe, 0xff]), bigEndian])
}

export interface XlsxSheetFixture {
  name: string
  rows: readonly (readonly Cell[])[]
  /** A1-notation merge ranges, e.g. `['A1:C1']` for a title banner. */
  merges?: readonly string[]
  /** Excel row numbers (1-based) to write as hidden, to check sheet filtering. */
  hidden?: boolean
}

/** Write a real .xlsx workbook (exceljs is already a reviewed dependency). */
export async function xlsxBytes(sheets: readonly XlsxSheetFixture[]): Promise<Buffer> {
  const ExcelJS = (await import('exceljs')).default
  const workbook = new ExcelJS.Workbook()
  for (const sheetFixture of sheets) {
    const sheet = workbook.addWorksheet(sheetFixture.name)
    for (const row of sheetFixture.rows) {
      sheet.addRow(row.map((cell) => (cell === null || cell === undefined ? null : cell)))
    }
    for (const range of sheetFixture.merges ?? []) sheet.mergeCells(range)
    if (sheetFixture.hidden) sheet.state = 'veryHidden'
  }
  const written = await workbook.xlsx.writeBuffer()
  return Buffer.from(written as ArrayBuffer)
}

/**
 * A few hundred thousand rows, generated by DuckDB's own `COPY ... TO` rather
 * than Node-side string building, matching
 * `tests/ingest-scale.integration.test.ts`'s approach. The temp CSV is read
 * back and deleted before the caller zips it, so only one copy is on disk at a
 * time (this machine's disk budget is tight).
 */
export async function largeRetailCsvBytes(rowCount: number): Promise<Buffer> {
  const directory = await mkdtemp(join(tmpdir(), 'dsh-vers-large-'))
  const path = join(directory, 'large.csv')
  const instance = await DuckDBInstance.create(':memory:')
  const connection = await instance.connect()
  try {
    await connection.run(
      `COPY (
         SELECT i::BIGINT AS line_id,
                'C' || lpad((i % 4000)::VARCHAR, 4, '0') AS customer_id,
                '2024-01-01'::DATE + (i % 28)::INTEGER AS order_date,
                'g' || (i % 7)::VARCHAR AS region,
                ((i % 100)::DOUBLE / 4) AS amount,
                (i * 2)::BIGINT AS quantity
         FROM range(${rowCount}) t(i)
       ) TO ? (FORMAT CSV, HEADER)`,
      [path],
    )
  } finally {
    connection.closeSync()
    instance.closeSync()
  }
  const bytes = await readFile(path)
  await rm(directory, { recursive: true, force: true })
  return bytes
}

/** Write arbitrary bytes to a fixture file inside `directory`. */
export async function writeFixtureFile(
  directory: string,
  name: string,
  bytes: Buffer | string,
): Promise<string> {
  const path = join(directory, name)
  await writeFile(path, bytes)
  return path
}

/** Read a written fixture back (used by gate tests that inspect the bytes). */
export async function readFixtureFile(path: string): Promise<Buffer> {
  return await readFile(path)
}
